# Generated by Django 4.2 on 2026-08-25 06:35

import App.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('employee_id', models.CharField(max_length=100, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('experience', models.PositiveIntegerField(default=0, help_text='Years of experience')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ASSIGNED_TO_AGENT', 'Assigned to Agent'), ('ACCEPTED', 'Accepted by Agent'), ('IN_PROGRESS', 'In Progress'), ('DOCUMENTS_COLLECTED', 'Documents Collected'), ('SUBMITTED_TO_UNIVERSITY', 'Submitted to University'), ('APPROVED', 'Approved by University'), ('REJECTED_BY_UNIVERSITY', 'Rejected by University'), ('ADDITIONAL_DOC_REQUIRED', 'Additional Documents Required'), ('COMPLETED', 'Completed'), ('REJECTED_BY_AGENT', 'Rejected by Agent'), ('DELIVERY_ASSIGNED', 'Delivery Agent Assigned'), ('PICKED_UP', 'Picked Up by Delivery Agent'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered Successfully')], default='ASSIGNED_TO_AGENT', max_length=30)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agent_rejection_reason', models.TextField(blank=True, null=True)),
                ('progress_note', models.TextField(blank=True, null=True)),
                ('admin_notified_rejection', models.BooleanField(default=False)),
                ('collected_document_url', models.URLField(blank=True, help_text='Scanned copy uploaded by agent', null=True)),
                ('courier_partner', models.CharField(blank=True, choices=[('Shiprocket', 'Shiprocket'), ('Delhivery', 'Delhivery'), ('BlueDart', 'BlueDart'), ('Other', 'Other')], max_length=50, null=True)),
                ('tracking_id', models.CharField(blank=True, max_length=100, null=True)),
                ('tracking_url', models.URLField(blank=True, null=True)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='App.agent')),
            ],
        ),
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('altPhone', models.CharField(max_length=15)),
                ('payment_status', models.CharField(default='Unpaid', max_length=20)),
                ('service_fee', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('requirement', models.CharField(max_length=50)),
                ('referenceNumber', models.CharField(blank=True, max_length=100, null=True)),
                ('termsAccepted', models.BooleanField(default=False)),
                ('specialCondition', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application_id', models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True)),
                ('tracking_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('admin_message', models.TextField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('agent', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(choices=[('pending_approval', 'Pending Approval'), ('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('changes_requested', 'Changes Requested'), ('completed', 'Completed')], default='pending_approval', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('location', models.CharField(max_length=255)),
                ('district', models.CharField(max_length=255)),
                ('pincode', models.CharField(max_length=10)),
                ('regType', models.CharField(choices=[('Private', 'Private'), ('Government', 'Government'), ('Autonomous', 'Autonomous'), ('University', 'University')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='DeliveryRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_id', models.CharField(max_length=100, unique=True)),
                ('student', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('item', models.CharField(max_length=255)),
                ('courier_partner', models.CharField(max_length=100)),
                ('current_location', models.CharField(max_length=255)),
                ('status', models.CharField(default='In Transit', max_length=50)),
                ('est_delivery', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImageUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='compressed/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('rating', models.IntegerField()),
                ('review', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('customer_id', models.CharField(default=App.models.generate_customer_id, editable=False, max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=10)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='UniversityVisitRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('visit_time', models.TimeField(blank=True, null=True)),
                ('department', models.CharField(blank=True, default='', max_length=255)),
                ('officer_name', models.CharField(blank=True, default='', max_length=255)),
                ('university_reference_number', models.CharField(blank=True, default='', max_length=255)),
                ('remarks', models.TextField(blank=True, default='')),
                ('university_fee_paid', models.BooleanField(default=False)),
                ('university_fee_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('chk_verified_student_info', models.BooleanField(default=False)),
                ('chk_submitted_application', models.BooleanField(default=False)),
                ('chk_verified_documents', models.BooleanField(default=False)),
                ('chk_met_officials', models.BooleanField(default=False)),
                ('chk_submitted_forms', models.BooleanField(default=False)),
                ('chk_paid_fees', models.BooleanField(default=False)),
                ('chk_recorded_reference_number', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visit_record', to='App.agentassignment')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityVisitPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.FileField(upload_to='visit_photos/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='App.universityvisitrecord')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityDecisionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('ADDITIONAL_DOCS', 'Additional Documents Required')], max_length=20)),
                ('officer_name', models.CharField(blank=True, default='', max_length=255)),
                ('remarks', models.TextField(blank=True, default='')),
                ('rejection_reason', models.CharField(blank=True, choices=[('Student Record Not Found', 'Student Record Not Found'), ('Incomplete Documents', 'Incomplete Documents'), ('Name Mismatch', 'Name Mismatch'), ('Pending University Fees', 'Pending University Fees'), ('Authorization Letter Missing', 'Authorization Letter Missing'), ('Duplicate Request', 'Duplicate Request'), ('University Policy Restriction', 'University Policy Restriction'), ('Other', 'Other')], max_length=100, null=True)),
                ('rejection_letter', models.FileField(blank=True, null=True, upload_to='rejection_letters/')),
                ('required_documents', models.TextField(blank=True, null=True)),
                ('deadline', models.DateField(blank=True, null=True)),
                ('university_reference_number', models.CharField(blank=True, max_length=255, null=True)),
                ('acceptance_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision_record', to='App.agentassignment')),
            ],
        ),
        migrations.CreateModel(
            name='TrackingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_history', to='App.application')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=255, unique=True)),
                ('payment_session_id', models.CharField(blank=True, max_length=255, null=True)),
                ('cf_payment_id', models.CharField(blank=True, max_length=255, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('status', models.CharField(default='PENDING', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='App.application')),
            ],
        ),
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.admin')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='App.users')),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_type', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='documents/')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='App.application')),
            ],
        ),
        migrations.CreateModel(
            name='Degree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100, null=True)),
                ('university', models.CharField(max_length=255)),
                ('course', models.CharField(blank=True, max_length=255, null=True)),
                ('college', models.CharField(max_length=255)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='degrees', to='App.application')),
            ],
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to='App.college')),
            ],
        ),
        migrations.AddField(
            model_name='agentassignment',
            name='application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_assignment', to='App.application'),
        ),
    ]
