# Generated by Django 4.2 on 2026-08-25 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_application_customer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='application',
            name='customer',
        ),
    ]
