# Generated by Django 6.0.3 on 2026-08-25 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_remove_application_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='application',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='installment_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_type',
            field=models.CharField(default='FULL', max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
