# Generated by Django 6.1 on 2026-08-26 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_application_paid_amount_application_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='user_acknowledged',
            field=models.BooleanField(default=False),
        ),
    ]
