# Generated by Django 4.2 on 2026-08-27 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_application_user_acknowledged'),
    ]

    operations = [
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('USER_RESPONDED', 'User Responded'), ('AGENT_REVIEWING', 'Agent Reviewing'), ('RESOLVED', 'Resolved')], default='OPEN', max_length=20)),
                ('user_response', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='issues', to='App.agent')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='App.application')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='App.users')),
            ],
        ),
    ]
