# Generated by Django 4.2 on 2026-08-27 04:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_issue'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='issue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='App.issue'),
        ),
        migrations.AddField(
            model_name='issue',
            name='required_documents',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Open'), ('WAITING_FOR_USER', 'Waiting For User'), ('USER_RESPONDED', 'User Responded'), ('UNDER_REVIEW', 'Under Review'), ('RESOLVED', 'Resolved')], default='WAITING_FOR_USER', max_length=20),
        ),
    ]
