# Generated by Django 4.2 on 2026-08-31 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_application_customer_usertoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAdminMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
                ('attachment', models.FileField(blank=True, null=True, upload_to='agent_admin_messages/')),
                ('is_from_admin', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='App.admin')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_messages', to='App.agent')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
