# Generated by Django 4.2 on 2026-08-31 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_agentadminmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentadminmessage',
            name='application',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agent_admin_messages', to='App.application'),
        ),
    ]
