# Generated by Django 4.2 on 2026-08-31 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_agentadminmessage_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentassignment',
            name='delivery_remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentassignment',
            name='dispatch_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='agentassignment',
            name='expected_delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
