# Generated by Django 4.2 on 2026-09-01 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0012_agentassignment_delivery_remarks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentassignment',
            name='courier_partner',
            field=models.CharField(blank=True, choices=[('Shiprocket', 'Shiprocket'), ('Delhivery', 'Delhivery'), ('BlueDart', 'BlueDart'), ('DTDC', 'DTDC'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
