# Generated by Django 4.2 on 2026-09-02 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_alter_agentassignment_courier_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentassignment',
            name='courier_partner',
            field=models.CharField(blank=True, choices=[('Shiprocket', 'Shiprocket'), ('Delhivery', 'Delhivery'), ('BlueDart', 'BlueDart'), ('Other', 'Other')], max_length=50, null=True),
        ),
    ]
