# Generated by Django 4.2.7 on 2026-09-08 04:15

import App.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_alter_agentassignment_courier_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentadminmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=App.models.agent_message_upload_path),
        ),
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(upload_to=App.models.document_upload_path),
        ),
    ]
