# Generated by Django 4.2.7 on 2026-09-10 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0015_alter_agentadminmessage_attachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='extra_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='application',
            name='extra_paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='application',
            name='extra_payment_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='application',
            name='extra_payment_status',
            field=models.CharField(default='NONE', max_length=20),
        ),
    ]
