# Generated by Django 4.2.7 on 2026-09-10 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_application_extra_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='total_amount_edit_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
