# Generated by Django 4.2 on 2026-07-20 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0030_application_application_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
