# Generated by Django 4.2 on 2026-07-20 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0032_alter_application_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('employee_id', models.CharField(max_length=100, unique=True)),
                ('mobile', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.CharField(blank=True, default='', max_length=255)),
                ('experience', models.PositiveIntegerField(default=0, help_text='Years of experience')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='AgentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ASSIGNED_TO_AGENT', 'Assigned to Agent'), ('ACCEPTED', 'Accepted by Agent'), ('IN_PROGRESS', 'In Progress'), ('DOCUMENTS_COLLECTED', 'Documents Collected'), ('SUBMITTED_TO_UNIVERSITY', 'Submitted to University'), ('COMPLETED', 'Completed'), ('REJECTED_BY_AGENT', 'Rejected by Agent')], default='ASSIGNED_TO_AGENT', max_length=30)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('agent_rejection_reason', models.TextField(blank=True, null=True)),
                ('progress_note', models.TextField(blank=True, null=True)),
                ('admin_notified_rejection', models.BooleanField(default=False)),
                ('agent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assignments', to='App.agent')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='agent_assignment', to='App.application')),
            ],
        ),
    ]
