# Generated by Django 4.2 on 2026-07-20 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0034_alter_application_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniversityVisit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateField(blank=True, null=True)),
                ('visit_time', models.TimeField(blank=True, null=True)),
                ('officer_name', models.CharField(blank=True, max_length=255)),
                ('department', models.CharField(blank=True, max_length=255)),
                ('remarks', models.TextField(blank=True)),
                ('reference_number', models.CharField(blank=True, max_length=255)),
                ('photo', models.FileField(blank=True, null=True, upload_to='visit_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='visit', to='App.agentassignment')),
            ],
        ),
        migrations.CreateModel(
            name='UniversityDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACCEPTED', 'Accepted'), ('REJECTED', 'Rejected'), ('DOCS_REQUIRED', 'Additional Documents Required'), ('UNDER_REVIEW', 'Under Review')], max_length=20)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('rejection_letter', models.FileField(blank=True, null=True, upload_to='rejection_letters/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='decision', to='App.agentassignment')),
            ],
        ),
        migrations.CreateModel(
            name='CollectedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='collected_docs/')),
                ('is_supporting', models.BooleanField(default=False)),
                ('seal_verified', models.BooleanField(default=False)),
                ('collection_date', models.DateField(auto_now_add=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='collected_docs', to='App.agentassignment')),
            ],
        ),
    ]
