# Generated by Django 4.2 on 2026-07-21 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0035_universityvisit_universitydecision_collecteddocument'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrackingHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracking_history', to='App.application')),
            ],
        ),
        migrations.RemoveField(
            model_name='universitydecision',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='universityvisit',
            name='assignment',
        ),
        migrations.AlterField(
            model_name='agentassignment',
            name='status',
            field=models.CharField(choices=[('ASSIGNED_TO_AGENT', 'Assigned to Agent'), ('ACCEPTED', 'Accepted by Agent'), ('IN_PROGRESS', 'In Progress'), ('DOCUMENTS_COLLECTED', 'Documents Collected'), ('SUBMITTED_TO_UNIVERSITY', 'Submitted to University'), ('COMPLETED', 'Completed'), ('REJECTED_BY_AGENT', 'Rejected by Agent'), ('DELIVERY_ASSIGNED', 'Delivery Agent Assigned'), ('PICKED_UP', 'Picked Up by Delivery Agent'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered Successfully')], default='ASSIGNED_TO_AGENT', max_length=30),
        ),
        migrations.DeleteModel(
            name='CollectedDocument',
        ),
        migrations.DeleteModel(
            name='UniversityDecision',
        ),
        migrations.DeleteModel(
            name='UniversityVisit',
        ),
    ]
