# Generated by Django 4.2 on 2026-07-21 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0037_add_logistics_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agentassignment',
            name='status',
            field=models.CharField(choices=[('ASSIGNED_TO_AGENT', 'Assigned to Agent'), ('ACCEPTED', 'Accepted by Agent'), ('IN_PROGRESS', 'In Progress'), ('DOCUMENTS_COLLECTED', 'Documents Collected'), ('SUBMITTED_TO_UNIVERSITY', 'Submitted to University'), ('APPROVED', 'Approved by University'), ('REJECTED_BY_UNIVERSITY', 'Rejected by University'), ('ADDITIONAL_DOC_REQUIRED', 'Additional Documents Required'), ('COMPLETED', 'Completed'), ('REJECTED_BY_AGENT', 'Rejected by Agent'), ('DELIVERY_ASSIGNED', 'Delivery Agent Assigned'), ('PICKED_UP', 'Picked Up by Delivery Agent'), ('OUT_FOR_DELIVERY', 'Out for Delivery'), ('DELIVERED', 'Delivered Successfully')], default='ASSIGNED_TO_AGENT', max_length=30),
        ),
    ]
