# Generated by Django 4.2 on 2026-07-21 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0038_alter_agentassignment_status'),
        ('App', '0038_university_visit_record'),
    ]

    operations = [
    ]
