"""
Django settings for Transcrits project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

SECRET_KEY = 'django-insecure-_qb@%u)m*q4h+9mp2h8vp2h8vp#tw7v_*p9-yl^gk4&wmsi)p8vlfa'

DEBUG = True

ALLOWED_HOSTS = ['*']


# ---------------------------------------------------------
# Application definition
# ---------------------------------------------------------

INSTALLED_APPS = [
    'daphne',                         
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'App',
    'rest_framework',
    'corsheaders',
    'channels',
]

CORS_ALLOW_ALL_ORIGINS = True


MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


ROOT_URLCONF = 'Transcripts.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'Transcripts.wsgi.application'


# Channels ASGI application
ASGI_APPLICATION = 'Transcripts.asgi.application'


# ---------------------------------------------------------
# Database
# ---------------------------------------------------------

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': '100Transcripts',
#         'USER': 'postgres',
#         'PASSWORD': 'Srini123',
#         'HOST': 'localhost',
#         'PORT': '5432',
#     }
# }


# ---------------------------------------------------------
# Environment
# ---------------------------------------------------------

load_dotenv(BASE_DIR.parent / ".env")


# ---------------------------------------------------------
# WhatsApp Interakt API Configuration
# ---------------------------------------------------------

WHATSAPP_ENABLED = os.getenv(
    "WHATSAPP_ENABLED",
    "False"
).lower() in ("true", "1", "t")

INTERAKT_SECRET_KEY = os.getenv(
    "INTERAKT_SECRET_KEY",
    ""
)

INTERAKT_BASE_URL = os.getenv(
    "INTERAKT_BASE_URL",
    "https://api.interakt.ai/v1/public/message/"
)

INTERAKT_TEMPLATE_NAME = os.getenv(
    "INTERAKT_TEMPLATE_NAME",
    ""
)


# ---------------------------------------------------------
# Email Configuration
# ---------------------------------------------------------

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 465
EMAIL_USE_SSL = True
EMAIL_USE_TLS = False

EMAIL_HOST_USER = os.getenv(
    "EMAIL_HOST_USER",
    "support@100Transcripts.com"
)

EMAIL_HOST_PASSWORD = os.getenv(
    "EMAIL_HOST_PASSWORD",
    ""
)


# ---------------------------------------------------------
# Cashfree
# ---------------------------------------------------------

CASHFREE_CLIENT_ID = os.getenv(
    "CASHFREE_CLIENT_ID"
)

CASHFREE_CLIENT_SECRET = os.getenv(
    "CASHFREE_CLIENT_SECRET"
)

CASHFREE_ENVIRONMENT = os.getenv(
    "CASHFREE_ENVIRONMENT"
)

FRONTEND_URL = os.getenv(
    "FRONTEND_URL",
    "http://localhost:5173"
)


# ---------------------------------------------------------
# CSRF
# ---------------------------------------------------------

CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
]


# ---------------------------------------------------------
# Channels + Redis
# ---------------------------------------------------------

CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [
                ('127.0.0.1', 6379),
            ],
        },
    },
}


# ---------------------------------------------------------
# Chat messages Redis storage
# ---------------------------------------------------------

CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.redis.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",
    }
}


# ---------------------------------------------------------
# Password validation
# ---------------------------------------------------------

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ---------------------------------------------------------
# Internationalization
# ---------------------------------------------------------

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# ---------------------------------------------------------
# Static / Media
# ---------------------------------------------------------

STATIC_URL = 'static/'

MEDIA_URL = '/media/'

MEDIA_ROOT = os.path.join(
    BASE_DIR,
    'media'
)


# ---------------------------------------------------------
# Default primary key
# ---------------------------------------------------------

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'